Update SignGUI prompt to support raw lines.
Add Registry support for modules.
Add Quest persistence support, now requires ID to be set.
(Might not work on /reload because of NoClassDefFoundError error, but I have no idea how to fix it.)